- .gitignore
- snowblocks/git/gitconfig
- snowblocks/git/gitconfig_auth
- snowblocks/git/snowblock.json
> Conditional includes

- snowblocks/git/gitconfig
> Closes #25
The branch printing aliases "b" and the extended aliases "bum" and "bm" have been simplified by removing unnecessary flags.
* The "--list" flag should be used to list branches matching a specific pattern
* The "-v"/"-vv"/"--verbose" flags which shows the commit SHA1 and subject
line after each branch has been removed
> Simplify branch printing aliases

- snowblocks/git/gitconfig
> Closes #24
* The defined ASCII colors codes for the output have been changed to
adapt to the terminal colors theme/scheme.
* The format has been simplified and minimized/reduced to relevant
information except the extended `ll` and `llf` aliases.
* Added the shorthand aliases `lf` and `llf` for a flattened output
without topic commits from merges and adapted the style to the
existing `lnew` and `lch` aliases.
* The `lr` alias is superfluous and has been removed due to the new
`ll` and `llf` aliases which include the relative date of a commit.
> Improved logging alias formats

- snowblocks/vim/vimrc
> Closes #22
Allows to move the cursor to the previous/next line after reaching first/last character in the line using the the left <kbd><</kbd> and <kbd>></kbd> arrow keys in normal-, insert- (`<,>`) and visual mode (`[,]`) or the <kbd>h</kbd> and <kbd>l</kbd> keys.
References:
`:help whichwrap`
> Automatically wrap left and right

- snowblocks/vim/vimrc
> Closes #21
The key mapping allows to easily move the current line or selected
block(s) using the <kbd>Ctrl</kbd> and the *up* <kbd>⇧</kbd> and *down* <kbd>⇩</kbd> keys.
* The moved line/block adapts to to the new indentation.
* The key mappings are available in the `NORMAL`, `INSERT` and `VISUAL` modes
> Add line- and block move key mappings

- snowblocks/vim/vimrc
> Enable sign column auto toggle

- snowblocks/vim/vimrc
> JSX syntax highlighting and indentation plugin

- snowblocks/bash/config/env/igloo
> Remove local Ruby and NPM modules from PATH

- snowblocks/pacman/pacman.conf.archbook
> Closes #49
PR #53 only removed the ignored packages for the `igloo` host.
> Removed ignored pacman packages for "archbook" host

- snowblocks/systemd/README.md
- snowblocks/systemd/snowblock.json
- snowblocks/systemd/units/user/igloosync-dropbox.service
- snowblocks/systemd/units/user/ssh-agent.service
> systemd user unit services

- snowblocks/git/git-diff-igloocrypt
- snowblocks/git/gitattributes
- snowblocks/git/gitconfig
- snowblocks/git/snowblock.json
> Transparent Git encryption using GPG

- snowblocks/bash/config/pkg/gradle
> GRADLE_OPTS

- snowblocks/git/gitconfig
> "diff-so-fancy" compatible "format-patch" alias

- snowblocks/bash/bin/dsf
> Use "diff-so-fancy" without Git

- snowblocks/bash/config/env/igloo
> Remove custom ATOM_HOME path

- snowblocks/firefox/user.js
> Fix tabs not rendered in titlebar

- snowblocks/bash/core/prompt
The exit status of last shell command should be determined at the very beginning of the `compile_prompt` function.
> Fix a bug in determing the exit status of last shell command

- snowblocks/firefox/user.js
> Disable automatic execution pause on script exceptions

- snowblocks/firefox/user.js
> Enable "legacy" user profile customizations

- snowblocks/ripgrep/config
- snowblocks/ripgrep/snowblock.json
<p align="center"><img src="https://camo.githubusercontent.com/f6c23a97909b858f9bc03039070fd98d524d3c86/68747470733a2f2f6275726e7473757368692e6e65742f73747566662f72697067726570312e706e67"align="center" /></p>
Closes #262
> "ripgrep" snowblock

- snowblocks/git/config.conf
> Disable command auto-correction

- snowblocks/zsh/pkgs/rsync/aliases.zsh
> Preserve executability with `cpr` alias

- snowblocks/zsh/lib/plugins.polarbear.zsh
> Fix missing root slashes in `fzf` absolute path of plugin loader script
