snowblocks/pacman/pacman.conf.archbook
snowblocks/pacman/pacman.conf.igloo

Everyone loves candies!

---

snowblocks/vim/vimrc

Remap syntax highlighting function

---

snowblocks/vim/vimrc

Enable 24bit true color support

---

snowblocks/vim/vimrc

Add Markdown plugin plasticboy/vim-markdown

---

snowblocks/vim/vimrc

Replace unmaintained vim-coloresque plugin

---

snowblocks/vim/vimrc

Add vim-livedown

---

snowblocks/pacman/pacman.conf.igloo

Removed ignored pacman packages

---

snowblocks/git/gitconfig_auth

Use long GPG keyid format for Git configuration

---

snowblocks/git/git-commit-msg

Adapt Git commit message template to style guide

---

.gitmodules
LICENSE.md
README.md
bootstrap
snowblocks/bash/bin/colors
snowblocks/bash/bin/keybase-stop
snowblocks/bash/bin/treed
snowblocks/bash/bootstrap
snowblocks/bash/config/env/igloo
snowblocks/bash/config/pkg/dircolors
snowblocks/bash/config/pkg/grep
snowblocks/bash/config/pkg/gulp
snowblocks/bash/config/pkg/history
snowblocks/bash/config/pkg/java
snowblocks/bash/config/pkg/less
snowblocks/bash/config/pkg/pacaur
snowblocks/bash/config/pkg/sudo
snowblocks/bash/core/aliases
snowblocks/bash/core/functions
snowblocks/bash/core/loader/env
snowblocks/bash/core/loader/pkg
snowblocks/bash/core/prompt
snowblocks/bash/core/shelloptions
snowblocks/git/git-commit-msg
snowblocks/git/gitconfig
snowblocks/git/gitignore
snowblocks/pacman/makepkg.conf
snowblocks/pacman/pacman.conf.archbook
snowblocks/pacman/pacman.conf.igloo
snowblocks/vim/vimrc

Migrate to the MIT license

---

snowblocks/vim/vimrc

Remove default enabled "list" option

---

snowblocks/vim/vimrc

Add and configure "NERD Commenter" plugin

---

snowblocks/bash/core/aliases

alias for file/directory mode bits (attributes) in octal notation format

---

snowblocks/git/gitconfig

Conditional configuration includes for "gitlab" and "incubator"

---

snowblocks/bash/core/aliases

Shortcut alias for "trash-cli"

---

snowflakes/udev/README.md
snowflakes/udev/rules/igloo-udev-logitech-r400-presenter.hwdb

udev scancode-to-keynode mapping for "Logitech R400 Presenter"

---

snowblocks/git/gitconfig

Autocorrect command typos

---

snowblocks/firefox/user.js

Disable third-party APIs for more privacy

---

snowblocks/firefox/user.js

Disable fullscreen warning popup

---

snowblocks/firefox/user.js

Disable automatic crash report sending

---

snowblocks/firefox/user.js

Use "Standard" option for "Enhanced Tracking Protection" privacy prefs

---

snowblocks/firefox/user.js

Enable more `about:debugging` options by default

---

snowblocks/firefox/user.js

Show CSS grid line numbers

---

snowblocks/firefox/user.js

Add “Inter“ as base sans-serif typeface

---

snowblocks/firefox/user.js

Define "soft" and USB WebAuthn development options

---

snowblocks/firefox/user.js

Disable password generation suggestion for password fields

---

snowblocks/bat/config
snowblocks/bat/snowblock.json

<p align="center"><img src="https://raw.githubusercontent.com/sharkdp/bat/master/doc/logo-header.svg?sanitize=true"align="center" /></p>
Closes #259

"bat" snowblock

---

snowblocks/broot/conf.toml
snowblocks/broot/snowblock.json

<p align="center"><img src="https://dystroy.org/broot/img/vache.svg" width="30%" align="center" /></p>
Closes #260

"broot" snowblock

---

snowblocks/procs/config.toml
snowblocks/procs/snowblock.json

<p align="center"><img src="https://user-images.githubusercontent.com/4331004/55446648-71729e00-55fb-11e9-8e12-1ca63911c568.png"align="center" /></p>
Closes #261

"procs" snowblock

---

snowblocks/wget/snowblock.json
snowblocks/wget/wgetrc

"Wget" snowblock

---

snowblocks/zsh/pkgs/dircolors/config.zsh

Fix missing guard for "dircolors" initialization

---

snowblocks/zsh/pkgs/coreutils/env.zsh

ISO-8601 compliant time style format for `date` command

---

snowblocks/zsh/README.md
snowblocks/zsh/config/zle.zsh
snowblocks/zsh/rc.zsh
snowblocks/zsh/snowblock.json

Customized ZLE word movement and modification

---

snowblocks/zsh/lib/themes/igloo.zsh
snowblocks/zsh/pkgs/git/config-base.zsh

Broken custom colors for Git integration in `igloo` theme

---

snowblocks/pueue/pueue.yaml
snowblocks/pueue/pueue_aliases.yaml
snowblocks/pueue/snowblock.json

<p align="center"><img src="https://raw.githubusercontent.com/Nukesor/images/main/pueue-v2.0.0.gif" width="666px" /></p>
Resolves #298

`pueue` snowblock
